### ISSUE TITLE
Should be "The Jungle Book" not "The Jungle Books"?

### ISSUE THREAD

**Issue by nicwest** [peter-dickinson-books/peterdickinson.com#2]
https://github.com/peter-dickinson-books/peterdickinson.com/commit/4abe0435d50e92fd0f7b448953d194bd7e94c94b#diff-bf7b920f1bf0836cb1b7e05c4bd69bf0R51

**Comment by PapaDelta55** [comment]
There were two Jungle books: 'The Jungle Book' and 'The Second Jungle Book'. Peter is referring to both books in this piece, so 'The Jungle Books' is correct in context.

**Comment by nicwest** [comment]
cool
